# Usa una imagen oficial de Tomcat 10.1 como imagen base
FROM tomcat:10.1

# Copia el archivo WAR en el directorio webapps de Tomcat
COPY target/springbootapp-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/springbootapp-0.0.1-SNAPSHOT.war